package dev.nerviz.bankapp.infrastructure.rest.openapi;

import dev.nerviz.bankapp.infrastructure.rest.dto.CreateCustomerRequest;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import org.springframework.http.ProblemDetail;

/** Goes on {@code CustomerApi#create} alone — {@code @PostMapping} lives on the controller. */
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
@Operation(
        summary = "Creates a customer",
        operationId = "createCustomer",
        parameters = {
            @Parameter(
                    name = "Idempotency-Key",
                    in = ParameterIn.HEADER,
                    required = true,
                    description = "UUID generated by the client. Repeating the request with the"
                            + " same key returns the stored response.",
                    example = "3fa85f64-5717-4562-b3fc-2c963f66afa6")
        },
        requestBody =
                @RequestBody(
                        required = true,
                        description = "Data of the customer to create",
                        content =
                                @Content(
                                        schema = @Schema(implementation = CreateCustomerRequest.class),
                                        examples = @ExampleObject(name = "minimal", value = """
                                                                {
                                                                  "name": "Maria Silva",
                                                                  "securityNumber": "12345678901",
                                                                  "birthDate": "1990-05-17"
                                                                }
                                                                """))))
@ApiResponse(responseCode = "201", description = "Created")
@ApiResponse(
        responseCode = "400",
        description = "Invalid body, or Idempotency-Key missing or malformed",
        content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
@ApiResponse(
        responseCode = "409",
        description = "Security number already registered, or Idempotency-Key reused with a different body",
        content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
@ApiResponse(
        responseCode = "422",
        description = "Customer is not strictly over 18 years old",
        content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
@ApiResponse(
        responseCode = "500",
        description = "Unmapped error",
        content = @Content(schema = @Schema(implementation = ProblemDetail.class)))
public @interface CreateCustomerOpenApiDocs {}
