// Generated by test-architect's setup mode (archunit-installer) — blueprint
// clean-architecture-single-module. Packages translated from
// .claude/skills/test-architect/templates/ArchitectureTest.java.example to this
// project's own packages.map and naming convention; do not copy rules back from the
// exemplar without the same translation.
package dev.nerviz.bankapp;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.classes;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.fields;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;
import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noFields;
import static com.tngtech.archunit.library.GeneralCodingRules.NO_CLASSES_SHOULD_ACCESS_STANDARD_STREAMS;
import static com.tngtech.archunit.library.GeneralCodingRules.NO_CLASSES_SHOULD_THROW_GENERIC_EXCEPTIONS;
import static com.tngtech.archunit.library.GeneralCodingRules.NO_CLASSES_SHOULD_USE_FIELD_INJECTION;
import static com.tngtech.archunit.library.GeneralCodingRules.NO_CLASSES_SHOULD_USE_JAVA_UTIL_LOGGING;

import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaField;
import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;
import com.tngtech.archunit.library.dependencies.SlicesRuleDefinition;
import java.time.Clock;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.Set;

@AnalyzeClasses(packages = "dev.nerviz.bankapp", importOptions = ImportOption.DoNotIncludeTests.class)
class ArchitectureTest {

    /**
     * Dependency direction (`.claude/rules/architecture-ddd.md`,
     * `dependency_rules.forbidden` of blueprint clean-architecture-single-module). The
     * project has no `adapter`/`bootstrap` packages — those are the hexagonal exemplar's
     * names — so only the two boundaries the blueprint actually declares are checked.
     */
    @ArchTest
    static final ArchRule domain_knows_no_one = noClasses()
            .that()
            .resideInAPackage("..domain..")
            .should()
            .dependOnClassesThat()
            .resideInAnyPackage("..application..", "..infrastructure..", "..commons..");

    @ArchTest
    static final ArchRule application_does_not_know_infrastructure = noClasses()
            .that()
            .resideInAPackage("..application..")
            .should()
            .dependOnClassesThat()
            .resideInAnyPackage("..infrastructure..");

    @ArchTest
    static final ArchRule no_cycles_between_packages = SlicesRuleDefinition.slices()
            .matching("dev.nerviz.bankapp.(*)..")
            .should()
            .beFreeOfCycles();

    /** Domain purity (`.claude/rules/architecture-ddd.md`, `.claude/forbidden-imports.txt`). */
    @ArchTest
    static final ArchRule domain_has_no_framework = noClasses()
            .that()
            .resideInAPackage("..domain..")
            .should()
            .dependOnClassesThat()
            .resideInAnyPackage("org.springframework..", "jakarta..", "com.fasterxml.jackson..", "tools.jackson..");

    @ArchTest
    static final ArchRule domain_has_no_system_clock = noClasses()
            .that()
            .resideInAPackage("..domain..")
            .should()
            .callMethod(LocalDateTime.class, "now")
            .orShould()
            .callMethod(LocalDate.class, "now")
            .orShould()
            .callMethod(Clock.class, "systemDefaultZone")
            .because("Clock is injected — see rules/architecture-ddd.md");

    /** Composition (`.claude/rules/architecture-ddd.md` § Composition). */
    @ArchTest
    static final ArchRule no_field_injection = NO_CLASSES_SHOULD_USE_FIELD_INJECTION;

    /**
     * `..infrastructure.config..` stands in for the exemplar's `..bootstrap..`: it's the
     * one package in this blueprint where Spring wiring legitimately touches the context
     * (root `CLAUDE.md` § Module structure — adapter-local wiring stays with its adapter,
     * but the generic `ApplicationContext` lookup, if any, belongs here, not an application
     * or domain class reaching for a service locator).
     */
    @ArchTest
    static final ArchRule no_service_locator = noClasses()
            .that()
            .resideOutsideOfPackage("..infrastructure.config..")
            .should()
            .dependOnClassesThat()
            .haveFullyQualifiedName("org.springframework.context.ApplicationContext");

    /** Naming (`.claude/rules/naming.md`). */
    @ArchTest
    static final ArchRule no_impl_suffix = noClasses()
            .should()
            .haveSimpleNameEndingWith("Impl")
            .because("the name says the role, not that it's the implementation of something");

    /**
     * `.and().areNotAssignableTo(Record.class)` on the two package-based role rules: a
     * record is a value carrier — a use case's `*Command`, a port's result record — never a
     * role, and it lives next to the role it serves. ArchUnit imports nested classes too, so
     * without it a result record declared inside the port interface fails "should be
     * interfaces", and a `Command` fails the suffix rule. A plain class out of pattern still
     * fails both.
     */
    @ArchTest
    static final ArchRule outbound_ports_are_interfaces = classes()
            .that()
            .resideInAPackage("..application.port..")
            .and()
            .areNotAssignableTo(Record.class)
            .should()
            .beInterfaces();

    /**
     * This blueprint's use case is the concrete class itself — `<Verb><Noun>UseCase`, no
     * separate `Service` implementation (`.claude/rules/naming.md` § Architecture
     * vocabulary) — unlike the hexagonal exemplar this rule was translated from, which
     * checks an `..application.service..` package for a `Service` suffix. Its `Command`
     * record is co-located in the same package and is already exempt by type.
     * `.and().haveSimpleNameNotEndingWith("package-info")` because `project-bootstrap`
     * generates a `package-info.java` in every package, and ArchUnit imports it as a class.
     */
    @ArchTest
    static final ArchRule use_case_classes_end_with_use_case = classes()
            .that()
            .resideInAPackage("..application.usecase..")
            .and()
            .haveSimpleNameNotEndingWith("package-info")
            .and()
            .areNotAssignableTo(Record.class)
            .should()
            .haveSimpleNameEndingWith("UseCase");

    @ArchTest
    static final ArchRule controllers_in_rest_adapter = classes()
            .that()
            .areAnnotatedWith("org.springframework.web.bind.annotation.RestController")
            .and()
            .haveSimpleNameNotEndingWith("package-info")
            .should()
            .resideInAPackage("..infrastructure.rest..")
            .andShould()
            .haveSimpleNameEndingWith("Controller");

    /**
     * The trailing two dots are deliberate: the persistence adapter is organized as one
     * subpackage per aggregate (`@.claude/rules/persistence.md` § Boundary), so the entity
     * of `Customer` resides in `..infrastructure.persistence.customer`. Narrowing this to a
     * single-level glob would fail every project that follows the rule.
     */
    @ArchTest
    static final ArchRule jpa_entities_have_entity_suffix = classes()
            .that()
            .areAnnotatedWith("jakarta.persistence.Entity")
            .and()
            .haveSimpleNameNotEndingWith("package-info")
            .should()
            .haveSimpleNameEndingWith("Entity")
            .andShould()
            .resideInAPackage("..infrastructure.persistence..");

    /**
     * Persistence mapping (`.claude/rules/persistence.md`). Both bugs the two rules below
     * catch pass compilation and most tests: the first degrades {@code save()} to
     * {@code merge()} and swallows primary-key collisions, the second only fails at context
     * startup.
     */
    private static final DescribedPredicate<JavaClass> HAVE_ASSIGNED_ID = DescribedPredicate.describe(
            "have an @Id without @GeneratedValue",
            javaClass -> javaClass.getAllFields().stream()
                    .anyMatch(field -> field.isAnnotatedWith("jakarta.persistence.Id")
                            && !field.isAnnotatedWith("jakarta.persistence.GeneratedValue")));

    /** Empty is allowed: a project whose ids are all generated has nothing to check. */
    @ArchTest
    static final ArchRule assigned_ids_implement_persistable = classes()
            .that()
            .areAnnotatedWith("jakarta.persistence.Entity")
            .and(HAVE_ASSIGNED_ID)
            .should()
            .implement("org.springframework.data.domain.Persistable")
            .because("without isNew, Spring Data merges instead of persisting (§ Identity and keys)")
            .allowEmptyShould(true);

    /**
     * Postgres only: `@Lob String` maps to `oid`, not `text`. Drop this rule when the
     * blueprint's database is another engine. Empty is the expected state: no {@code @Lob}
     * field at all.
     */
    @ArchTest
    static final ArchRule no_lob_on_string = noFields()
            .that()
            .areAnnotatedWith("jakarta.persistence.Lob")
            .should()
            .haveRawType(String.class)
            .because("a bare String already maps to text (§ Mapping)")
            .allowEmptyShould(true);

    /** Code quality (`.claude/rules/code-quality.md`). */
    @ArchTest
    static final ArchRule no_generic_exceptions = NO_CLASSES_SHOULD_THROW_GENERIC_EXCEPTIONS;

    @ArchTest
    static final ArchRule private_final_fields_in_domain = fields().that()
            .areDeclaredInClassesThat()
            .resideInAPackage("..domain..")
            .and()
            .areNotStatic()
            .should()
            .bePrivate()
            .andShould()
            .beFinal()
            .because("value objects and aggregates are immutable");

    @ArchTest
    static final ArchRule no_java_util_logging = NO_CLASSES_SHOULD_USE_JAVA_UTIL_LOGGING;

    @ArchTest
    static final ArchRule no_system_out = NO_CLASSES_SHOULD_ACCESS_STANDARD_STREAMS;

    /**
     * Masking (`.claude/rules/logging.md` § Masking candidates). The global REST aspect logs
     * request and response DTOs BY DEFAULT, opt-out. So a DTO that carries personal data and
     * does not implement the masking interface leaks it the moment the endpoint runs — which
     * is how a {@code String securityNumber} holding a CPF crossed design, implementation,
     * review and a green build in a real project. The type half of the derivation needs no
     * list: a field whose raw type is one of the catalog's personal-data value objects
     * matches by type. SENSITIVE_NAMES is copied verbatim from logging.md § Masking
     * candidates — it is the rule's list, shortening it here is how a field stops being
     * checked.
     */
    private static final Set<String> SENSITIVE_NAMES = Set.of(
            "cpf",
            "cnpj",
            "rg",
            "ssn",
            "taxid",
            "nationalid",
            "securitynumber",
            "socialsecurity",
            "document",
            "documento",
            "documentnumber",
            "passport",
            "driverlicense",
            "email",
            "phone",
            "telefone",
            "celular",
            "mobile",
            "whatsapp",
            "address",
            "endereco",
            "street",
            "logradouro",
            "zipcode",
            "cep",
            "postalcode",
            "birthdate",
            "datanascimento",
            "dateofbirth",
            "card",
            "cardnumber",
            "cvv",
            "cvc",
            "iban",
            "pix",
            "accountnumber",
            "agency",
            "password",
            "senha",
            "secret",
            "token",
            "apikey",
            "accesskey",
            "privatekey");

    private static final String LOG_MASK = "dev.nerviz.bankapp.commons.logging.interfaces.LogMask";
    private static final String MASK_SENSITIVE = "dev.nerviz.bankapp.commons.logging.annotations.MaskSensitiveData";

    /**
     * The guard, and it has to be on the `that()` side. `should().implement("...")` against
     * an interface that is not on the classpath FAILS for every matched class — it does not
     * skip — so `allowEmptyShould` alone would turn "commons not installed" into a red
     * build. Matching nothing is what makes the rule vacuous until `commons.logging` lands.
     */
    private static final boolean COMMONS_INSTALLED = isOnClasspath(LOG_MASK);

    private static boolean isOnClasspath(String fqn) {
        try {
            Class.forName(fqn, false, ArchitectureTest.class.getClassLoader());
            return true;
        } catch (ClassNotFoundException e) {
            return false;
        }
    }

    private static final Set<String> SENSITIVE_TYPES = Set.of("Email", "PhoneNumber", "Cpf", "Cnpj", "Document");

    private static final DescribedPredicate<JavaField> SENSITIVE_FIELD =
            DescribedPredicate.describe("be derived as sensitive by name or by type", field -> {
                if (!COMMONS_INSTALLED) return false;
                String name = field.getName().toLowerCase(Locale.ROOT);
                return SENSITIVE_NAMES.stream().anyMatch(name::contains)
                        || SENSITIVE_TYPES.contains(field.getRawType().getSimpleName());
            });

    private static final DescribedPredicate<JavaClass> CARRY_SENSITIVE_DATA = DescribedPredicate.describe(
            "carry a field the masking rule derives as sensitive",
            javaClass -> javaClass.getAllFields().stream().anyMatch(SENSITIVE_FIELD));

    /**
     * Guarded: {@code commons.logging} is installed on demand, not at bootstrap. Where the
     * masking interface does not exist on the classpath the predicate matches nothing and
     * {@code allowEmptyShould(true)} keeps the rule vacuous instead of failing a project that
     * never installed it — or one with no sensitive DTO yet.
     */
    @ArchTest
    static final ArchRule sensitive_dtos_implement_log_mask = classes()
            .that()
            .resideInAPackage("..infrastructure.rest.dto..")
            .and(CARRY_SENSITIVE_DATA)
            .should()
            .implement(LOG_MASK)
            .because("the REST aspect logs every DTO by default; an unmasked one leaks the field"
                    + " (@.claude/rules/logging.md § Masking candidates)")
            .allowEmptyShould(true);

    /**
     * The interface alone gives a masked `toString()` only for the fields that say which
     * pattern to use. A class that implements it and marks nothing masks nothing.
     */
    @ArchTest
    static final ArchRule sensitive_fields_are_marked = fields().that()
            .areDeclaredInClassesThat()
            .resideInAPackage("..infrastructure.rest.dto..")
            .and()
            .areDeclaredInClassesThat()
            .implement(LOG_MASK)
            .and(SENSITIVE_FIELD)
            .should()
            .beAnnotatedWith(MASK_SENSITIVE)
            .because("masking is per field, and the default is to mask"
                    + " (@.claude/rules/logging.md § Masking candidates)")
            .allowEmptyShould(true);
}
